### ISSUE TITLE
Down

### ISSUE THREAD

**Issue by rspearson** [giop98/cycle#6]
Hello. Is the site down? Cant get to it from multiple devices. Thanks, Richard

**Comment by giovannipollo** [comment]
Hi. Yes, unluckily the game is not playable anymore, because there were issues with the original version of the game, WORDLE. So the repo will still be open source, but I cannot publicly host the game anymore.

**Comment by rspearson** [comment]
Ah thats such a shame. Pity, but thanks for letting me know.
